# Generated by Django 5.0.7 on 2024-08-26 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='profiles',
        ),
    ]
