# Generated by Django 5.0.7 on 2024-08-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
