# Generated by Django 5.0.7 on 2024-09-01 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_userprofile_profile_image'),
        ('catalog', '0008_alter_dish_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreatedDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/user_dishes/')),
                ('recipes', models.TextField(null=True)),
                ('proteins', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('kcals', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('products', models.ManyToManyField(blank=True, to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_created_dishes',
            },
        ),
        migrations.CreateModel(
            name='UserDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dishes', to='catalog.dish')),
                ('ingredients', models.ManyToManyField(blank=True, to='catalog.recipeingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_dishes',
            },
        ),
    ]
