# Generated by Django 5.0.7 on 2024-09-02 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_usercreateddish_userdish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdish',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='userdish',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='userdish',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserCreatedDish',
        ),
        migrations.DeleteModel(
            name='UserDish',
        ),
    ]
