# Generated by Django 5.0.7 on 2024-07-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('proteins', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kcals', models.DecimalField(decimal_places=2, max_digits=5)),
                ('products', models.ManyToManyField(db_table='dishes_products', to='catalog.product')),
            ],
            options={
                'db_table': 'dishes',
            },
        ),
    ]
