# Generated by Django 5.0.7 on 2024-08-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='areas',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='categorys',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='recipes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='areas',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='categorys',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
