# Generated by Django 5.0.7 on 2024-08-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_dish_products_alter_recipeingredient_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/dishes/'),
        ),
    ]
