# Generated by Django 5.0.7 on 2024-09-02 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_dish_user_usercreateddish_userdish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='user',
        ),
    ]
