# Generated by Django 5.0.7 on 2024-09-03 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_usercreateddish_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreatedDishProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.usercreateddish')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'db_table': 'user_created_dish_products',
                'unique_together': {('dish', 'product')},
            },
        ),
    ]
